// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: judge.proto

package judgepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Verdict int32

const (
	Verdict_VERDICT_UNSPECIFIED Verdict = 0
	Verdict_VERDICT_BLOCK       Verdict = 1
	Verdict_VERDICT_ALLOW       Verdict = 2
)

// Enum value maps for Verdict.
var (
	Verdict_name = map[int32]string{
		0: "VERDICT_UNSPECIFIED",
		1: "VERDICT_BLOCK",
		2: "VERDICT_ALLOW",
	}
	Verdict_value = map[string]int32{
		"VERDICT_UNSPECIFIED": 0,
		"VERDICT_BLOCK":       1,
		"VERDICT_ALLOW":       2,
	}
)

func (x Verdict) Enum() *Verdict {
	p := new(Verdict)
	*p = x
	return p
}

func (x Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_judge_proto_enumTypes[0].Descriptor()
}

func (Verdict) Type() protoreflect.EnumType {
	return &file_judge_proto_enumTypes[0]
}

func (x Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict.Descriptor instead.
func (Verdict) EnumDescriptor() ([]byte, []int) {
	return file_judge_proto_rawDescGZIP(), []int{0}
}

type JudgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputText     string                 `protobuf:"bytes,1,opt,name=input_text,json=inputText,proto3" json:"input_text,omitempty"`
	Context       *RuleContext           `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	RuleSetId     string                 `protobuf:"bytes,3,opt,name=rule_set_id,json=ruleSetId,proto3" json:"rule_set_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JudgeRequest) Reset() {
	*x = JudgeRequest{}
	mi := &file_judge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JudgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeRequest) ProtoMessage() {}

func (x *JudgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_judge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeRequest.ProtoReflect.Descriptor instead.
func (*JudgeRequest) Descriptor() ([]byte, []int) {
	return file_judge_proto_rawDescGZIP(), []int{0}
}

func (x *JudgeRequest) GetInputText() string {
	if x != nil {
		return x.InputText
	}
	return ""
}

func (x *JudgeRequest) GetContext() *RuleContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *JudgeRequest) GetRuleSetId() string {
	if x != nil {
		return x.RuleSetId
	}
	return ""
}

type RuleContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversation  []*ConversationTurn    `protobuf:"bytes,1,rep,name=conversation,proto3" json:"conversation,omitempty"`
	IndexedRoots  []string               `protobuf:"bytes,2,rep,name=indexed_roots,json=indexedRoots,proto3" json:"indexed_roots,omitempty"`
	Worktree      *WorktreeState         `protobuf:"bytes,3,opt,name=worktree,proto3" json:"worktree,omitempty"`
	Cwd           string                 `protobuf:"bytes,4,opt,name=cwd,proto3" json:"cwd,omitempty"`
	CwdIndexed    string                 `protobuf:"bytes,5,opt,name=cwd_indexed,json=cwdIndexed,proto3" json:"cwd_indexed,omitempty"` // "yes" | "no"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleContext) Reset() {
	*x = RuleContext{}
	mi := &file_judge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleContext) ProtoMessage() {}

func (x *RuleContext) ProtoReflect() protoreflect.Message {
	mi := &file_judge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleContext.ProtoReflect.Descriptor instead.
func (*RuleContext) Descriptor() ([]byte, []int) {
	return file_judge_proto_rawDescGZIP(), []int{1}
}

func (x *RuleContext) GetConversation() []*ConversationTurn {
	if x != nil {
		return x.Conversation
	}
	return nil
}

func (x *RuleContext) GetIndexedRoots() []string {
	if x != nil {
		return x.IndexedRoots
	}
	return nil
}

func (x *RuleContext) GetWorktree() *WorktreeState {
	if x != nil {
		return x.Worktree
	}
	return nil
}

func (x *RuleContext) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *RuleContext) GetCwdIndexed() string {
	if x != nil {
		return x.CwdIndexed
	}
	return ""
}

type ConversationTurn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationTurn) Reset() {
	*x = ConversationTurn{}
	mi := &file_judge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationTurn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationTurn) ProtoMessage() {}

func (x *ConversationTurn) ProtoReflect() protoreflect.Message {
	mi := &file_judge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationTurn.ProtoReflect.Descriptor instead.
func (*ConversationTurn) Descriptor() ([]byte, []int) {
	return file_judge_proto_rawDescGZIP(), []int{2}
}

func (x *ConversationTurn) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ConversationTurn) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type WorktreeState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PrimaryCheckout string                 `protobuf:"bytes,1,opt,name=primary_checkout,json=primaryCheckout,proto3" json:"primary_checkout,omitempty"`
	DefaultBranch   string                 `protobuf:"bytes,2,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"`
	Worktrees       []*Worktree            `protobuf:"bytes,3,rep,name=worktrees,proto3" json:"worktrees,omitempty"`
	CurrentWorktree string                 `protobuf:"bytes,4,opt,name=current_worktree,json=currentWorktree,proto3" json:"current_worktree,omitempty"`
	CurrentBranch   string                 `protobuf:"bytes,5,opt,name=current_branch,json=currentBranch,proto3" json:"current_branch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorktreeState) Reset() {
	*x = WorktreeState{}
	mi := &file_judge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorktreeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorktreeState) ProtoMessage() {}

func (x *WorktreeState) ProtoReflect() protoreflect.Message {
	mi := &file_judge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorktreeState.ProtoReflect.Descriptor instead.
func (*WorktreeState) Descriptor() ([]byte, []int) {
	return file_judge_proto_rawDescGZIP(), []int{3}
}

func (x *WorktreeState) GetPrimaryCheckout() string {
	if x != nil {
		return x.PrimaryCheckout
	}
	return ""
}

func (x *WorktreeState) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

func (x *WorktreeState) GetWorktrees() []*Worktree {
	if x != nil {
		return x.Worktrees
	}
	return nil
}

func (x *WorktreeState) GetCurrentWorktree() string {
	if x != nil {
		return x.CurrentWorktree
	}
	return ""
}

func (x *WorktreeState) GetCurrentBranch() string {
	if x != nil {
		return x.CurrentBranch
	}
	return ""
}

type Worktree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,3,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Worktree) Reset() {
	*x = Worktree{}
	mi := &file_judge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worktree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worktree) ProtoMessage() {}

func (x *Worktree) ProtoReflect() protoreflect.Message {
	mi := &file_judge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worktree.ProtoReflect.Descriptor instead.
func (*Worktree) Descriptor() ([]byte, []int) {
	return file_judge_proto_rawDescGZIP(), []int{4}
}

func (x *Worktree) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Worktree) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *Worktree) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

type JudgeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdict       Verdict                `protobuf:"varint,1,opt,name=verdict,proto3,enum=judge.v1.Verdict" json:"verdict,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JudgeReply) Reset() {
	*x = JudgeReply{}
	mi := &file_judge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JudgeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JudgeReply) ProtoMessage() {}

func (x *JudgeReply) ProtoReflect() protoreflect.Message {
	mi := &file_judge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JudgeReply.ProtoReflect.Descriptor instead.
func (*JudgeReply) Descriptor() ([]byte, []int) {
	return file_judge_proto_rawDescGZIP(), []int{5}
}

func (x *JudgeReply) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_UNSPECIFIED
}

func (x *JudgeReply) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *JudgeReply) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type ListRuleSetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuleSetsRequest) Reset() {
	*x = ListRuleSetsRequest{}
	mi := &file_judge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuleSetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuleSetsRequest) ProtoMessage() {}

func (x *ListRuleSetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_judge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuleSetsRequest.ProtoReflect.Descriptor instead.
func (*ListRuleSetsRequest) Descriptor() ([]byte, []int) {
	return file_judge_proto_rawDescGZIP(), []int{6}
}

type ListRuleSetsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleSets      []*RuleSetDescriptor   `protobuf:"bytes,1,rep,name=rule_sets,json=ruleSets,proto3" json:"rule_sets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuleSetsReply) Reset() {
	*x = ListRuleSetsReply{}
	mi := &file_judge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuleSetsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuleSetsReply) ProtoMessage() {}

func (x *ListRuleSetsReply) ProtoReflect() protoreflect.Message {
	mi := &file_judge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuleSetsReply.ProtoReflect.Descriptor instead.
func (*ListRuleSetsReply) Descriptor() ([]byte, []int) {
	return file_judge_proto_rawDescGZIP(), []int{7}
}

func (x *ListRuleSetsReply) GetRuleSets() []*RuleSetDescriptor {
	if x != nil {
		return x.RuleSets
	}
	return nil
}

type RuleSetDescriptor struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                  // "search-guard", "worktree-guard"
	RequiredContext []string               `protobuf:"bytes,2,rep,name=required_context,json=requiredContext,proto3" json:"required_context,omitempty"` // "conversation","indexed_roots","worktree"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RuleSetDescriptor) Reset() {
	*x = RuleSetDescriptor{}
	mi := &file_judge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleSetDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSetDescriptor) ProtoMessage() {}

func (x *RuleSetDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_judge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSetDescriptor.ProtoReflect.Descriptor instead.
func (*RuleSetDescriptor) Descriptor() ([]byte, []int) {
	return file_judge_proto_rawDescGZIP(), []int{8}
}

func (x *RuleSetDescriptor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RuleSetDescriptor) GetRequiredContext() []string {
	if x != nil {
		return x.RequiredContext
	}
	return nil
}

var File_judge_proto protoreflect.FileDescriptor

const file_judge_proto_rawDesc = "" +
	"\n" +
	"\vjudge.proto\x12\bjudge.v1\"~\n" +
	"\fJudgeRequest\x12\x1d\n" +
	"\n" +
	"input_text\x18\x01 \x01(\tR\tinputText\x12/\n" +
	"\acontext\x18\x02 \x01(\v2\x15.judge.v1.RuleContextR\acontext\x12\x1e\n" +
	"\vrule_set_id\x18\x03 \x01(\tR\truleSetId\"\xda\x01\n" +
	"\vRuleContext\x12>\n" +
	"\fconversation\x18\x01 \x03(\v2\x1a.judge.v1.ConversationTurnR\fconversation\x12#\n" +
	"\rindexed_roots\x18\x02 \x03(\tR\findexedRoots\x123\n" +
	"\bworktree\x18\x03 \x01(\v2\x17.judge.v1.WorktreeStateR\bworktree\x12\x10\n" +
	"\x03cwd\x18\x04 \x01(\tR\x03cwd\x12\x1f\n" +
	"\vcwd_indexed\x18\x05 \x01(\tR\n" +
	"cwdIndexed\":\n" +
	"\x10ConversationTurn\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\xe5\x01\n" +
	"\rWorktreeState\x12)\n" +
	"\x10primary_checkout\x18\x01 \x01(\tR\x0fprimaryCheckout\x12%\n" +
	"\x0edefault_branch\x18\x02 \x01(\tR\rdefaultBranch\x120\n" +
	"\tworktrees\x18\x03 \x03(\v2\x12.judge.v1.WorktreeR\tworktrees\x12)\n" +
	"\x10current_worktree\x18\x04 \x01(\tR\x0fcurrentWorktree\x12%\n" +
	"\x0ecurrent_branch\x18\x05 \x01(\tR\rcurrentBranch\"U\n" +
	"\bWorktree\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x03 \x01(\bR\tisPrimary\"q\n" +
	"\n" +
	"JudgeReply\x12+\n" +
	"\averdict\x18\x01 \x01(\x0e2\x11.judge.v1.VerdictR\averdict\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\"\x15\n" +
	"\x13ListRuleSetsRequest\"M\n" +
	"\x11ListRuleSetsReply\x128\n" +
	"\trule_sets\x18\x01 \x03(\v2\x1b.judge.v1.RuleSetDescriptorR\bruleSets\"N\n" +
	"\x11RuleSetDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x10required_context\x18\x02 \x03(\tR\x0frequiredContext*H\n" +
	"\aVerdict\x12\x17\n" +
	"\x13VERDICT_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rVERDICT_BLOCK\x10\x01\x12\x11\n" +
	"\rVERDICT_ALLOW\x10\x022\x8d\x01\n" +
	"\x05Judge\x128\n" +
	"\bEvaluate\x12\x16.judge.v1.JudgeRequest\x1a\x14.judge.v1.JudgeReply\x12J\n" +
	"\fListRuleSets\x12\x1d.judge.v1.ListRuleSetsRequest\x1a\x1b.judge.v1.ListRuleSetsReplyB#Z!goodkind.io/lm-review/api/judgepbb\x06proto3"

var (
	file_judge_proto_rawDescOnce sync.Once
	file_judge_proto_rawDescData []byte
)

func file_judge_proto_rawDescGZIP() []byte {
	file_judge_proto_rawDescOnce.Do(func() {
		file_judge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_judge_proto_rawDesc), len(file_judge_proto_rawDesc)))
	})
	return file_judge_proto_rawDescData
}

var file_judge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_judge_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_judge_proto_goTypes = []any{
	(Verdict)(0),                // 0: judge.v1.Verdict
	(*JudgeRequest)(nil),        // 1: judge.v1.JudgeRequest
	(*RuleContext)(nil),         // 2: judge.v1.RuleContext
	(*ConversationTurn)(nil),    // 3: judge.v1.ConversationTurn
	(*WorktreeState)(nil),       // 4: judge.v1.WorktreeState
	(*Worktree)(nil),            // 5: judge.v1.Worktree
	(*JudgeReply)(nil),          // 6: judge.v1.JudgeReply
	(*ListRuleSetsRequest)(nil), // 7: judge.v1.ListRuleSetsRequest
	(*ListRuleSetsReply)(nil),   // 8: judge.v1.ListRuleSetsReply
	(*RuleSetDescriptor)(nil),   // 9: judge.v1.RuleSetDescriptor
}
var file_judge_proto_depIdxs = []int32{
	2, // 0: judge.v1.JudgeRequest.context:type_name -> judge.v1.RuleContext
	3, // 1: judge.v1.RuleContext.conversation:type_name -> judge.v1.ConversationTurn
	4, // 2: judge.v1.RuleContext.worktree:type_name -> judge.v1.WorktreeState
	5, // 3: judge.v1.WorktreeState.worktrees:type_name -> judge.v1.Worktree
	0, // 4: judge.v1.JudgeReply.verdict:type_name -> judge.v1.Verdict
	9, // 5: judge.v1.ListRuleSetsReply.rule_sets:type_name -> judge.v1.RuleSetDescriptor
	1, // 6: judge.v1.Judge.Evaluate:input_type -> judge.v1.JudgeRequest
	7, // 7: judge.v1.Judge.ListRuleSets:input_type -> judge.v1.ListRuleSetsRequest
	6, // 8: judge.v1.Judge.Evaluate:output_type -> judge.v1.JudgeReply
	8, // 9: judge.v1.Judge.ListRuleSets:output_type -> judge.v1.ListRuleSetsReply
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_judge_proto_init() }
func file_judge_proto_init() {
	if File_judge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_judge_proto_rawDesc), len(file_judge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_judge_proto_goTypes,
		DependencyIndexes: file_judge_proto_depIdxs,
		EnumInfos:         file_judge_proto_enumTypes,
		MessageInfos:      file_judge_proto_msgTypes,
	}.Build()
	File_judge_proto = out.File
	file_judge_proto_goTypes = nil
	file_judge_proto_depIdxs = nil
}
