// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: inference.proto

package inferencepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InferenceStatus int32

const (
	InferenceStatus_INFERENCE_STATUS_UNSPECIFIED InferenceStatus = 0
	InferenceStatus_INFERENCE_STATUS_COMPLETE    InferenceStatus = 1
)

// Enum value maps for InferenceStatus.
var (
	InferenceStatus_name = map[int32]string{
		0: "INFERENCE_STATUS_UNSPECIFIED",
		1: "INFERENCE_STATUS_COMPLETE",
	}
	InferenceStatus_value = map[string]int32{
		"INFERENCE_STATUS_UNSPECIFIED": 0,
		"INFERENCE_STATUS_COMPLETE":    1,
	}
)

func (x InferenceStatus) Enum() *InferenceStatus {
	p := new(InferenceStatus)
	*p = x
	return p
}

func (x InferenceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InferenceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_inference_proto_enumTypes[0].Descriptor()
}

func (InferenceStatus) Type() protoreflect.EnumType {
	return &file_inference_proto_enumTypes[0]
}

func (x InferenceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InferenceStatus.Descriptor instead.
func (InferenceStatus) EnumDescriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{0}
}

type InferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Input         string                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	OutputSchema  string                 `protobuf:"bytes,3,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"`
	Context       string                 `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferRequest) Reset() {
	*x = InferRequest{}
	mi := &file_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferRequest) ProtoMessage() {}

func (x *InferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferRequest.ProtoReflect.Descriptor instead.
func (*InferRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{0}
}

func (x *InferRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *InferRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

func (x *InferRequest) GetOutputSchema() string {
	if x != nil {
		return x.OutputSchema
	}
	return ""
}

func (x *InferRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *InferRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type InferReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OutputJson    string                 `protobuf:"bytes,1,opt,name=output_json,json=outputJson,proto3" json:"output_json,omitempty"`
	Status        InferenceStatus        `protobuf:"varint,2,opt,name=status,proto3,enum=inference.v1.InferenceStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InferReply) Reset() {
	*x = InferReply{}
	mi := &file_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InferReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InferReply) ProtoMessage() {}

func (x *InferReply) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InferReply.ProtoReflect.Descriptor instead.
func (*InferReply) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{1}
}

func (x *InferReply) GetOutputJson() string {
	if x != nil {
		return x.OutputJson
	}
	return ""
}

func (x *InferReply) GetStatus() InferenceStatus {
	if x != nil {
		return x.Status
	}
	return InferenceStatus_INFERENCE_STATUS_UNSPECIFIED
}

var File_inference_proto protoreflect.FileDescriptor

const file_inference_proto_rawDesc = "" +
	"\n" +
	"\x0finference.proto\x12\finference.v1\"\x91\x01\n" +
	"\fInferRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05input\x18\x02 \x01(\tR\x05input\x12#\n" +
	"\routput_schema\x18\x03 \x01(\tR\foutputSchema\x12\x18\n" +
	"\acontext\x18\x04 \x01(\tR\acontext\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\"d\n" +
	"\n" +
	"InferReply\x12\x1f\n" +
	"\voutput_json\x18\x01 \x01(\tR\n" +
	"outputJson\x125\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1d.inference.v1.InferenceStatusR\x06status*R\n" +
	"\x0fInferenceStatus\x12 \n" +
	"\x1cINFERENCE_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19INFERENCE_STATUS_COMPLETE\x10\x012J\n" +
	"\tInference\x12=\n" +
	"\x05Infer\x12\x1a.inference.v1.InferRequest\x1a\x18.inference.v1.InferReplyB'Z%goodkind.io/lm-review/api/inferencepbb\x06proto3"

var (
	file_inference_proto_rawDescOnce sync.Once
	file_inference_proto_rawDescData []byte
)

func file_inference_proto_rawDescGZIP() []byte {
	file_inference_proto_rawDescOnce.Do(func() {
		file_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)))
	})
	return file_inference_proto_rawDescData
}

var file_inference_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_inference_proto_goTypes = []any{
	(InferenceStatus)(0), // 0: inference.v1.InferenceStatus
	(*InferRequest)(nil), // 1: inference.v1.InferRequest
	(*InferReply)(nil),   // 2: inference.v1.InferReply
}
var file_inference_proto_depIdxs = []int32{
	0, // 0: inference.v1.InferReply.status:type_name -> inference.v1.InferenceStatus
	1, // 1: inference.v1.Inference.Infer:input_type -> inference.v1.InferRequest
	2, // 2: inference.v1.Inference.Infer:output_type -> inference.v1.InferReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_inference_proto_init() }
func file_inference_proto_init() {
	if File_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_proto_goTypes,
		DependencyIndexes: file_inference_proto_depIdxs,
		EnumInfos:         file_inference_proto_enumTypes,
		MessageInfos:      file_inference_proto_msgTypes,
	}.Build()
	File_inference_proto = out.File
	file_inference_proto_goTypes = nil
	file_inference_proto_depIdxs = nil
}
