// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.1
// source: review.proto

package reviewpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LMReviewD_Review_FullMethodName       = "/lmreview.LMReviewD/Review"
	LMReviewD_ReviewStatic_FullMethodName = "/lmreview.LMReviewD/ReviewStatic"
)

// LMReviewDClient is the client API for LMReviewD service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LMReviewDClient interface {
	Review(ctx context.Context, in *ReviewRequest, opts ...grpc.CallOption) (*ReviewResponse, error)
	ReviewStatic(ctx context.Context, in *StaticReviewRequest, opts ...grpc.CallOption) (*ReviewResponse, error)
}

type lMReviewDClient struct {
	cc grpc.ClientConnInterface
}

func NewLMReviewDClient(cc grpc.ClientConnInterface) LMReviewDClient {
	return &lMReviewDClient{cc}
}

func (c *lMReviewDClient) Review(ctx context.Context, in *ReviewRequest, opts ...grpc.CallOption) (*ReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewResponse)
	err := c.cc.Invoke(ctx, LMReviewD_Review_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lMReviewDClient) ReviewStatic(ctx context.Context, in *StaticReviewRequest, opts ...grpc.CallOption) (*ReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewResponse)
	err := c.cc.Invoke(ctx, LMReviewD_ReviewStatic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LMReviewDServer is the server API for LMReviewD service.
// All implementations must embed UnimplementedLMReviewDServer
// for forward compatibility.
type LMReviewDServer interface {
	Review(context.Context, *ReviewRequest) (*ReviewResponse, error)
	ReviewStatic(context.Context, *StaticReviewRequest) (*ReviewResponse, error)
	mustEmbedUnimplementedLMReviewDServer()
}

// UnimplementedLMReviewDServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLMReviewDServer struct{}

func (UnimplementedLMReviewDServer) Review(context.Context, *ReviewRequest) (*ReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Review not implemented")
}
func (UnimplementedLMReviewDServer) ReviewStatic(context.Context, *StaticReviewRequest) (*ReviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewStatic not implemented")
}
func (UnimplementedLMReviewDServer) mustEmbedUnimplementedLMReviewDServer() {}
func (UnimplementedLMReviewDServer) testEmbeddedByValue()                   {}

// UnsafeLMReviewDServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LMReviewDServer will
// result in compilation errors.
type UnsafeLMReviewDServer interface {
	mustEmbedUnimplementedLMReviewDServer()
}

func RegisterLMReviewDServer(s grpc.ServiceRegistrar, srv LMReviewDServer) {
	// If the following call panics, it indicates UnimplementedLMReviewDServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LMReviewD_ServiceDesc, srv)
}

func _LMReviewD_Review_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LMReviewDServer).Review(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LMReviewD_Review_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LMReviewDServer).Review(ctx, req.(*ReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LMReviewD_ReviewStatic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StaticReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LMReviewDServer).ReviewStatic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LMReviewD_ReviewStatic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LMReviewDServer).ReviewStatic(ctx, req.(*StaticReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LMReviewD_ServiceDesc is the grpc.ServiceDesc for LMReviewD service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LMReviewD_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lmreview.LMReviewD",
	HandlerType: (*LMReviewDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Review",
			Handler:    _LMReviewD_Review_Handler,
		},
		{
			MethodName: "ReviewStatic",
			Handler:    _LMReviewD_ReviewStatic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "review.proto",
}
