// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: review.proto

package reviewpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReviewMode int32

const (
	ReviewMode_REVIEW_MODE_UNSPECIFIED   ReviewMode = 0
	ReviewMode_REVIEW_MODE_AUTO          ReviewMode = 1
	ReviewMode_REVIEW_MODE_STAGED_DIFF   ReviewMode = 2
	ReviewMode_REVIEW_MODE_WORKTREE_DIFF ReviewMode = 3
	ReviewMode_REVIEW_MODE_PR            ReviewMode = 4
	ReviewMode_REVIEW_MODE_REPO          ReviewMode = 5
)

// Enum value maps for ReviewMode.
var (
	ReviewMode_name = map[int32]string{
		0: "REVIEW_MODE_UNSPECIFIED",
		1: "REVIEW_MODE_AUTO",
		2: "REVIEW_MODE_STAGED_DIFF",
		3: "REVIEW_MODE_WORKTREE_DIFF",
		4: "REVIEW_MODE_PR",
		5: "REVIEW_MODE_REPO",
	}
	ReviewMode_value = map[string]int32{
		"REVIEW_MODE_UNSPECIFIED":   0,
		"REVIEW_MODE_AUTO":          1,
		"REVIEW_MODE_STAGED_DIFF":   2,
		"REVIEW_MODE_WORKTREE_DIFF": 3,
		"REVIEW_MODE_PR":            4,
		"REVIEW_MODE_REPO":          5,
	}
)

func (x ReviewMode) Enum() *ReviewMode {
	p := new(ReviewMode)
	*p = x
	return p
}

func (x ReviewMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReviewMode) Descriptor() protoreflect.EnumDescriptor {
	return file_review_proto_enumTypes[0].Descriptor()
}

func (ReviewMode) Type() protoreflect.EnumType {
	return &file_review_proto_enumTypes[0]
}

func (x ReviewMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReviewMode.Descriptor instead.
func (ReviewMode) EnumDescriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{0}
}

type ReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          ReviewMode             `protobuf:"varint,1,opt,name=mode,proto3,enum=lmreview.ReviewMode" json:"mode,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                      // absolute path to repo root
	Depth         string                 `protobuf:"bytes,3,opt,name=depth,proto3" json:"depth,omitempty"`                    // quick | normal | deep | ultra (empty = normal)
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`                    // override model for this request (empty = use config)
	BaseRef       string                 `protobuf:"bytes,5,opt,name=base_ref,json=baseRef,proto3" json:"base_ref,omitempty"` // optional base ref for PR mode
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewRequest) Reset() {
	*x = ReviewRequest{}
	mi := &file_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewRequest) ProtoMessage() {}

func (x *ReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewRequest.ProtoReflect.Descriptor instead.
func (*ReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewRequest) GetMode() ReviewMode {
	if x != nil {
		return x.Mode
	}
	return ReviewMode_REVIEW_MODE_UNSPECIFIED
}

func (x *ReviewRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReviewRequest) GetDepth() string {
	if x != nil {
		return x.Depth
	}
	return ""
}

func (x *ReviewRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ReviewRequest) GetBaseRef() string {
	if x != nil {
		return x.BaseRef
	}
	return ""
}

type ReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdict       string                 `protobuf:"bytes,1,opt,name=verdict,proto3" json:"verdict,omitempty"` // pass | warn | block
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Issues        []*Issue               `protobuf:"bytes,5,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewResponse) Reset() {
	*x = ReviewResponse{}
	mi := &file_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewResponse) ProtoMessage() {}

func (x *ReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewResponse.ProtoReflect.Descriptor instead.
func (*ReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{1}
}

func (x *ReviewResponse) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *ReviewResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ReviewResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ReviewResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ReviewResponse) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

type StaticReviewRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Path            string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                                              // absolute path to repo root
	Files           []string               `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`                                            // optional relative file set
	DisabledSources []string               `protobuf:"bytes,3,rep,name=disabled_sources,json=disabledSources,proto3" json:"disabled_sources,omitempty"` // vet | staticcheck | custom | semgrep
	EnabledChecks   []string               `protobuf:"bytes,4,rep,name=enabled_checks,json=enabledChecks,proto3" json:"enabled_checks,omitempty"`       // exact check allowlist
	Synthesize      bool                   `protobuf:"varint,5,opt,name=synthesize,proto3" json:"synthesize,omitempty"`                                 // false = raw findings only
	Depth           string                 `protobuf:"bytes,6,opt,name=depth,proto3" json:"depth,omitempty"`                                            // quick | normal | deep | ultra (only for synthesize mode)
	Model           string                 `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`                                            // optional model override (only for synthesize mode)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StaticReviewRequest) Reset() {
	*x = StaticReviewRequest{}
	mi := &file_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticReviewRequest) ProtoMessage() {}

func (x *StaticReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticReviewRequest.ProtoReflect.Descriptor instead.
func (*StaticReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{2}
}

func (x *StaticReviewRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *StaticReviewRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *StaticReviewRequest) GetDisabledSources() []string {
	if x != nil {
		return x.DisabledSources
	}
	return nil
}

func (x *StaticReviewRequest) GetEnabledChecks() []string {
	if x != nil {
		return x.EnabledChecks
	}
	return nil
}

func (x *StaticReviewRequest) GetSynthesize() bool {
	if x != nil {
		return x.Synthesize
	}
	return false
}

func (x *StaticReviewRequest) GetDepth() string {
	if x != nil {
		return x.Depth
	}
	return ""
}

func (x *StaticReviewRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type Issue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"` // error | warning | info
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Line          int32                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Rule          string                 `protobuf:"bytes,4,opt,name=rule,proto3" json:"rule,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"` // style | security | performance | ...
	EndLine       int32                  `protobuf:"varint,7,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	Suggestion    string                 `protobuf:"bytes,8,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	Confidence    string                 `protobuf:"bytes,9,opt,name=confidence,proto3" json:"confidence,omitempty"` // high | medium | low
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_review_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{3}
}

func (x *Issue) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Issue) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Issue) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Issue) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *Issue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Issue) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Issue) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *Issue) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

func (x *Issue) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

var File_review_proto protoreflect.FileDescriptor

const file_review_proto_rawDesc = "" +
	"\n" +
	"\freview.proto\x12\blmreview\"\x94\x01\n" +
	"\rReviewRequest\x12(\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x14.lmreview.ReviewModeR\x04mode\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\tR\x05depth\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x19\n" +
	"\bbase_ref\x18\x05 \x01(\tR\abaseRef\"\xa2\x01\n" +
	"\x0eReviewResponse\x12\x18\n" +
	"\averdict\x18\x01 \x01(\tR\averdict\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\x12'\n" +
	"\x06issues\x18\x05 \x03(\v2\x0f.lmreview.IssueR\x06issues\"\xdd\x01\n" +
	"\x13StaticReviewRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05files\x18\x02 \x03(\tR\x05files\x12)\n" +
	"\x10disabled_sources\x18\x03 \x03(\tR\x0fdisabledSources\x12%\n" +
	"\x0eenabled_checks\x18\x04 \x03(\tR\renabledChecks\x12\x1e\n" +
	"\n" +
	"synthesize\x18\x05 \x01(\bR\n" +
	"synthesize\x12\x14\n" +
	"\x05depth\x18\x06 \x01(\tR\x05depth\x12\x14\n" +
	"\x05model\x18\a \x01(\tR\x05model\"\xf0\x01\n" +
	"\x05Issue\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x12\n" +
	"\x04rule\x18\x04 \x01(\tR\x04rule\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x19\n" +
	"\bend_line\x18\a \x01(\x05R\aendLine\x12\x1e\n" +
	"\n" +
	"suggestion\x18\b \x01(\tR\n" +
	"suggestion\x12\x1e\n" +
	"\n" +
	"confidence\x18\t \x01(\tR\n" +
	"confidence*\xa5\x01\n" +
	"\n" +
	"ReviewMode\x12\x1b\n" +
	"\x17REVIEW_MODE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10REVIEW_MODE_AUTO\x10\x01\x12\x1b\n" +
	"\x17REVIEW_MODE_STAGED_DIFF\x10\x02\x12\x1d\n" +
	"\x19REVIEW_MODE_WORKTREE_DIFF\x10\x03\x12\x12\n" +
	"\x0eREVIEW_MODE_PR\x10\x04\x12\x14\n" +
	"\x10REVIEW_MODE_REPO\x10\x052\x91\x01\n" +
	"\tLMReviewD\x12;\n" +
	"\x06Review\x12\x17.lmreview.ReviewRequest\x1a\x18.lmreview.ReviewResponse\x12G\n" +
	"\fReviewStatic\x12\x1d.lmreview.StaticReviewRequest\x1a\x18.lmreview.ReviewResponseB$Z\"goodkind.io/lm-review/api/reviewpbb\x06proto3"

var (
	file_review_proto_rawDescOnce sync.Once
	file_review_proto_rawDescData []byte
)

func file_review_proto_rawDescGZIP() []byte {
	file_review_proto_rawDescOnce.Do(func() {
		file_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_proto_rawDesc), len(file_review_proto_rawDesc)))
	})
	return file_review_proto_rawDescData
}

var file_review_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_review_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_review_proto_goTypes = []any{
	(ReviewMode)(0),             // 0: lmreview.ReviewMode
	(*ReviewRequest)(nil),       // 1: lmreview.ReviewRequest
	(*ReviewResponse)(nil),      // 2: lmreview.ReviewResponse
	(*StaticReviewRequest)(nil), // 3: lmreview.StaticReviewRequest
	(*Issue)(nil),               // 4: lmreview.Issue
}
var file_review_proto_depIdxs = []int32{
	0, // 0: lmreview.ReviewRequest.mode:type_name -> lmreview.ReviewMode
	4, // 1: lmreview.ReviewResponse.issues:type_name -> lmreview.Issue
	1, // 2: lmreview.LMReviewD.Review:input_type -> lmreview.ReviewRequest
	3, // 3: lmreview.LMReviewD.ReviewStatic:input_type -> lmreview.StaticReviewRequest
	2, // 4: lmreview.LMReviewD.Review:output_type -> lmreview.ReviewResponse
	2, // 5: lmreview.LMReviewD.ReviewStatic:output_type -> lmreview.ReviewResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_review_proto_init() }
func file_review_proto_init() {
	if File_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_proto_rawDesc), len(file_review_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_review_proto_goTypes,
		DependencyIndexes: file_review_proto_depIdxs,
		EnumInfos:         file_review_proto_enumTypes,
		MessageInfos:      file_review_proto_msgTypes,
	}.Build()
	File_review_proto = out.File
	file_review_proto_goTypes = nil
	file_review_proto_depIdxs = nil
}
