// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: review.proto

package reviewpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Diff          string                 `protobuf:"bytes,1,opt,name=diff,proto3" json:"diff,omitempty"`
	Deep          bool                   `protobuf:"varint,2,opt,name=deep,proto3" json:"deep,omitempty"`
	Context       string                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"` // optional extra context (e.g. PR title)
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`     // override model for this request (empty = use config)
	Path          string                 `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`       // absolute path to repo root for project-local rule loading
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewRequest) Reset() {
	*x = ReviewRequest{}
	mi := &file_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewRequest) ProtoMessage() {}

func (x *ReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewRequest.ProtoReflect.Descriptor instead.
func (*ReviewRequest) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewRequest) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

func (x *ReviewRequest) GetDeep() bool {
	if x != nil {
		return x.Deep
	}
	return false
}

func (x *ReviewRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *ReviewRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ReviewRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdict       string                 `protobuf:"bytes,1,opt,name=verdict,proto3" json:"verdict,omitempty"` // pass | warn | block
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Issues        []*Issue               `protobuf:"bytes,5,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewResponse) Reset() {
	*x = ReviewResponse{}
	mi := &file_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewResponse) ProtoMessage() {}

func (x *ReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewResponse.ProtoReflect.Descriptor instead.
func (*ReviewResponse) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{1}
}

func (x *ReviewResponse) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *ReviewResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ReviewResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ReviewResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ReviewResponse) GetIssues() []*Issue {
	if x != nil {
		return x.Issues
	}
	return nil
}

type Issue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Severity      string                 `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"` // error | warning | info
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Line          int32                  `protobuf:"varint,3,opt,name=line,proto3" json:"line,omitempty"`
	Rule          string                 `protobuf:"bytes,4,opt,name=rule,proto3" json:"rule,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"` // style | security | performance | ...
	EndLine       int32                  `protobuf:"varint,7,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	Suggestion    string                 `protobuf:"bytes,8,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	Confidence    string                 `protobuf:"bytes,9,opt,name=confidence,proto3" json:"confidence,omitempty"` // high | medium | low
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Issue) Reset() {
	*x = Issue{}
	mi := &file_review_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Issue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Issue) ProtoMessage() {}

func (x *Issue) ProtoReflect() protoreflect.Message {
	mi := &file_review_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Issue.ProtoReflect.Descriptor instead.
func (*Issue) Descriptor() ([]byte, []int) {
	return file_review_proto_rawDescGZIP(), []int{2}
}

func (x *Issue) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Issue) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Issue) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Issue) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *Issue) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Issue) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Issue) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *Issue) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

func (x *Issue) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

var File_review_proto protoreflect.FileDescriptor

const file_review_proto_rawDesc = "" +
	"\n" +
	"\freview.proto\x12\blmreview\"{\n" +
	"\rReviewRequest\x12\x12\n" +
	"\x04diff\x18\x01 \x01(\tR\x04diff\x12\x12\n" +
	"\x04deep\x18\x02 \x01(\bR\x04deep\x12\x18\n" +
	"\acontext\x18\x03 \x01(\tR\acontext\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04path\x18\x05 \x01(\tR\x04path\"\xa2\x01\n" +
	"\x0eReviewResponse\x12\x18\n" +
	"\averdict\x18\x01 \x01(\tR\averdict\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\x12'\n" +
	"\x06issues\x18\x05 \x03(\v2\x0f.lmreview.IssueR\x06issues\"\xf0\x01\n" +
	"\x05Issue\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x03 \x01(\x05R\x04line\x12\x12\n" +
	"\x04rule\x18\x04 \x01(\tR\x04rule\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x19\n" +
	"\bend_line\x18\a \x01(\x05R\aendLine\x12\x1e\n" +
	"\n" +
	"suggestion\x18\b \x01(\tR\n" +
	"suggestion\x12\x1e\n" +
	"\n" +
	"confidence\x18\t \x01(\tR\n" +
	"confidence2\xcc\x01\n" +
	"\tLMReviewD\x12?\n" +
	"\n" +
	"ReviewDiff\x12\x17.lmreview.ReviewRequest\x1a\x18.lmreview.ReviewResponse\x12=\n" +
	"\bReviewPR\x12\x17.lmreview.ReviewRequest\x1a\x18.lmreview.ReviewResponse\x12?\n" +
	"\n" +
	"ReviewRepo\x12\x17.lmreview.ReviewRequest\x1a\x18.lmreview.ReviewResponseB$Z\"goodkind.io/lm-review/api/reviewpbb\x06proto3"

var (
	file_review_proto_rawDescOnce sync.Once
	file_review_proto_rawDescData []byte
)

func file_review_proto_rawDescGZIP() []byte {
	file_review_proto_rawDescOnce.Do(func() {
		file_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_review_proto_rawDesc), len(file_review_proto_rawDesc)))
	})
	return file_review_proto_rawDescData
}

var file_review_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_review_proto_goTypes = []any{
	(*ReviewRequest)(nil),  // 0: lmreview.ReviewRequest
	(*ReviewResponse)(nil), // 1: lmreview.ReviewResponse
	(*Issue)(nil),          // 2: lmreview.Issue
}
var file_review_proto_depIdxs = []int32{
	2, // 0: lmreview.ReviewResponse.issues:type_name -> lmreview.Issue
	0, // 1: lmreview.LMReviewD.ReviewDiff:input_type -> lmreview.ReviewRequest
	0, // 2: lmreview.LMReviewD.ReviewPR:input_type -> lmreview.ReviewRequest
	0, // 3: lmreview.LMReviewD.ReviewRepo:input_type -> lmreview.ReviewRequest
	1, // 4: lmreview.LMReviewD.ReviewDiff:output_type -> lmreview.ReviewResponse
	1, // 5: lmreview.LMReviewD.ReviewPR:output_type -> lmreview.ReviewResponse
	1, // 6: lmreview.LMReviewD.ReviewRepo:output_type -> lmreview.ReviewResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_review_proto_init() }
func file_review_proto_init() {
	if File_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_review_proto_rawDesc), len(file_review_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_review_proto_goTypes,
		DependencyIndexes: file_review_proto_depIdxs,
		MessageInfos:      file_review_proto_msgTypes,
	}.Build()
	File_review_proto = out.File
	file_review_proto_goTypes = nil
	file_review_proto_depIdxs = nil
}
